### ISSUE TITLE
great that i found this

### ISSUE THREAD

**Issue by natxopedreira** [jacopomaroli/intel-neural-compute-stick-2-raspberry-pi-zero#1]
Hello

I was in need to compile openvino to armv6l and didnt know where begin, i was previously cross compiled... but i was lost.

So im going to follow your documentation but i have a first question. I dont see you use a docker image or anything i can recognize, so how is the process? you compile on al x86 linux machine and later pass the files to the pi?

Thank you

**Comment by jacopomaroli** [comment]
Hey, glad this guide finally might come useful to somebody :)

Yes you are correct:
It's not using docker, it's using qemu which is an emulator. It's basically the same technology you use when you run the android emulator in Android Studio (if you ever had the chance).
You then copy the binaries to the the pi

**Comment by natxopedreira** [comment]
Super!!

Im going to try right now

**Comment by natxopedreira** [comment]
Im not a pro user on linux so i dont understand this

`If you now use cat -v | head -n 10 or od -c | head -n 10 you'll see the fingerprint of the executable we need to identify the architecture (this step is just to show the reasoning behind the next line)`

I get an error executing this command 
Head require an argument -- c

That executable we are talking about?

**Comment by jacopomaroli** [comment]
That's just to show you the general theory behind the next command if you want to learn.
You can skip that, but if you're interested you can read more about it here https://linoxide.com/linux-how-to/linux-hexdump-command-examples/
the command requires a filename
`cat -v [filename] | head -n 10` or `od -c [filename] | head -n 1`
as instance
`cat -v ~/raspbian/bin/bash | head -n 10` 
I'll make that point more clear

**Comment by natxopedreira** [comment]
Ah.... ok - thanks a lot!!!!

Sorry to ask again but this, gives me an error
`sudo cp /usr/local/bin/qemu-arm ~/raspbian/usr/local/bin/qemu-arm`

because local do not exist so i changed to 
`sudo cp /usr/local/bin/qemu-arm ~/raspbian/usr/bin/qemu-arm`

but now i get `«/debootstrap/debootstrap»: No such file or directory`
sudo chroot ~/raspbian /debootstrap/debootstrap --second-stage

**Comment by jacopomaroli** [comment]
mmm can you try `sudo apt install debootstrap` and give it another go?
I might have missed it in the guide as I had it already installed on my system.
I'll update it if that's the case

**Comment by natxopedreira** [comment]
it says is currently installed.. but in spanish :)
`Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
debootstrap ya está en su versión más reciente (1.0.95ubuntu0.6).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 12 no actualizados.`

that means error executing... No such file or directory
`chroot: fallo al ejecutar la orden «/debootstrap/debootstrap»: No such file or directory`

**Comment by natxopedreira** [comment]
Just tried several times, and even inside a docker image so do not mess with my install.... but im not able to follow all steps.

Can i ask you if you can share the compiled version?

**Comment by jacopomaroli** [comment]
I shared the archives with you privately as I'm not sure about Intel licensing for distribution.
Good news is I'm getting the same error myself, it seems something due to qemu.
I'll keep investigating and post the solution and an update to the guide when I'm done.
I might kindly ask you to validate the fix by then :)

can you try to `sudo chroot ~/raspbian`? I think you'll get the infamous `chroot: failed to run command ‘/bin/bash’: No such file or directory`

**Comment by natxopedreira** [comment]
You are right!!!!, i get exactly that error
`chroot: fallo al ejecutar la orden «/bin/bash»: No such file or directory`

How did you shared the libs?

Im happy to test what you need as even you kindly shared the libs !thank you so much! im interested in to be able to compile myself for future uses

**Comment by jacopomaroli** [comment]
I got your gmail address from your github profile and shared it through gdrive.

I'd be interested into having an automated build system and at least distribute a building environment until I sort out if the license allows me to distribute binaries for openvino. the idea is leveraging github actions to have the whole pipeline open

**Comment by natxopedreira** [comment]
Ah ok, i see, thank you!!

I see opencv? can you also share the openvino ones?

I like your idea, openvino support for rpi is very very poor, for example with the current releases exist a bug since 2019 versions that does not allow you to use a more recent models. You can not use IRV10 ones...

I have this Dockfile that allows to compile "but in armv7" from source including opencv with intel support for inference
[https://gist.github.com/natxopedreira/f5467dea8b9f267e0a39e0cad422e37d](https://gist.github.com/natxopedreira/f5467dea8b9f267e0a39e0cad422e37d)

Im not a pro in crosscompiling/linux, but i will be happy to help you !!!

**Comment by jacopomaroli** [comment]
I just tried to share it again, let me know if it works.

Awesome, thanks for offering to help. I guess for the moment would be just gettin through the next steps in the guide as soon as I manage to find the issue.
I'll ping you as I find a fix :)

I think this project will become more relevant when I'll be able to confirm it works for both armv6/7 and automatically provide up to date binaries. (maybe encompassing x86-64 and *.deb packages as well)

It should work for both arm architectures as it's natively compiled in qemu. Just didn't have the time to test it

**Comment by natxopedreira** [comment]
Thank you, i get the libs...  im going to try them..

Sure, let me know when you found a fix and i will help, having this to work in armv6/v7 will be super !!!!

IMO will be nice to compile also opencv with intel backend support, to do inference, so you can choose if you want IECore or Opencv dnn.

In the gist you can see the flags needed to do that, opencv api to do that is nice and very fast... i think is faster that IECore

**Comment by natxopedreira** [comment]
Sorry to disturb again...

I asume that the libs worked ok for you... did you try in c++, im getting undefined symbol in InferenceEngine::Core::LoadNetwork and im linking the libs. In fact my project was working... only that was trowing a segfault because i was compiling in armv6

**Comment by jacopomaroli** [comment]
Are you compiling on the raspi, or are you running a binary and getting that error? At the end of the guide there are some guidelines to run an example. Does that work for you?

**Comment by natxopedreira** [comment]
Hello

Yes im compiling on rpi a c++ app that im able to "compile  using standard" libs, but when i replaced to new ones i get that error.

I will try following your gideline and let you know but i dont understand what can be the cause

P.D. maybe that helps finding whats happening with qemu on the guide im able to run a rpi qemu image following this [https://tkrel.com/7390](https://tkrel.com/7390) but compiling the version mentioned in your guide

**Comment by natxopedreira** [comment]
I was able to compile opencv and openvino (github master branch) in armv6 following this link you posted [https://solarianprogrammer.com/2019/08/07/cross-compile-opencv-raspberry-pi-zero-raspbian/](https://solarianprogrammer.com/2019/08/07/cross-compile-opencv-raspberry-pi-zero-raspbian/) and mixing with your notes.

To do not mess with my actual system i used a virtualbox debian 10 image

**Comment by jacopomaroli** [comment]
That's great news man, I'm so happy for you! I'm sorry I couldn't be more helpful but this problem hunted me a lot during the first time I went through the process and I was unable to pinpoint the issue.

Do you happen to know exactly what the problem was?
Did you have to install another version of QEMU or the one you compiled was fine? 
How about the undefined `InferenceEngine::Core::LoadNetwork`?

**Comment by natxopedreira** [comment]
You help me a lot.

Im not sure what was the problem... i can tell you what i have tried:

+ install default package of qemu static ---not work
+ compiled version you mentioned --not work
+ docker image with those option ---not work
+ virtualbox image debian 8 --works, not remember if compiled qemu or install default package

Undefined `InferenceEngine::Core::LoadNetwork` was a very curious one, my erro was that i had an old LIBRARY_PATH var and that was doing something wreid because previos declaration in code works ok... but that not.

Is also curious that even i set my backend to MYRIAD my CPU usage is very high, maybe is because im running async.

Are you getting good performance on pi zero?

**Comment by natxopedreira** [comment]
im also curious about how where you able to compile openvino from a  package, i tried and get ngraph errors because the is no code in ngraph folder as is need to  ` git submodule init && git submodule update --recursive`  and not possible on the package version, would like to know what im doing wrong in that approach

**Comment by natxopedreira** [comment]
Hello @jacopomaroli 

Sorry to disturb, but i can not find the answer myself, in your document you download a release 
wget https://github.com/openvinotoolkit/openvino/archive/2020.2.tar.gz

And later compile that release, but (please correct me if im wrong) you need to download git submodules for that project to sucessful compile.... how can you do that if the release you compiled is not a git repo? I mean if you do git submodule init && git submodule update --recursive it will not work so you have a ade an ngraph empty folders

Thank you!
